/*
 * Static OpenAPI document of Push API resource
 *
 * Push API resources Open API documentation
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Databox.Model;
using Databox.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Databox.Test.Model
{
    /// <summary>
    ///  Class for testing PayloadModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayloadModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PayloadModel
        //private PayloadModel instance;

        public PayloadModelTests()
        {
            // TODO uncomment below to create an instance of PayloadModel
            //instance = new PayloadModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PayloadModel
        /// </summary>
        [Fact]
        public void PayloadModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" PayloadModel
            //Assert.IsType<PayloadModel>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
