/*
 * Static OpenAPI document of Push API resource
 *
 * Push API resources Open API documentation
 *
 * The version of the OpenAPI document: 0.3.15-sdk.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Databox.Model;
using Databox.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Databox.Test.Model
{
    /// <summary>
    ///  Class for testing PayloadDataModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayloadDataModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PayloadDataModel
        //private PayloadDataModel instance;

        public PayloadDataModelTests()
        {
            // TODO uncomment below to create an instance of PayloadDataModel
            //instance = new PayloadDataModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PayloadDataModel
        /// </summary>
        [Fact]
        public void PayloadDataModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" PayloadDataModel
            //Assert.IsType<PayloadDataModel>(instance);
        }

        /// <summary>
        /// Test the property 'MetricName'
        /// </summary>
        [Fact]
        public void MetricNameTest()
        {
            // TODO unit test for the property 'MetricName'
        }

        /// <summary>
        /// Test the property 'DimensionName'
        /// </summary>
        [Fact]
        public void DimensionNameTest()
        {
            // TODO unit test for the property 'DimensionName'
        }

        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Fact]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }

        /// <summary>
        /// Test the property 'PeriodFrom'
        /// </summary>
        [Fact]
        public void PeriodFromTest()
        {
            // TODO unit test for the property 'PeriodFrom'
        }

        /// <summary>
        /// Test the property 'PeriodTo'
        /// </summary>
        [Fact]
        public void PeriodToTest()
        {
            // TODO unit test for the property 'PeriodTo'
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
    }
}
